services:
  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service-local
    ports:
      - "8001:8001"
    env_file:
      - ./services/auth-service/.env.local
    depends_on:
      - auth-postgres
      - job-tracker-redis

  application-service:
    build:
      context: ./services/application-service
    container_name: application-service-local
    ports:
      - "8002:8002"
    env_file:
      - ./services/application-service/.env.local
    depends_on:
      - auth-postgres
      - job-tracker-redis

  job-tracker-redis:
    image: redis:7
    container_name: job-tracker-redis-local
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: careerledger-rabbitmq-local
    ports:
      - "5672:5672"
      - "15672:15672"

  auth-postgres:
    image: postgres:16
    container_name: auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

volumes:
  auth_postgres_data: