services:
  auth-postgres:
    image: postgres:16
    container_name: auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    ports:
      - "8001:8001"
    env_file:
      - ./services/auth-service/.env.docker
    depends_on:
      - auth-postgres

volumes:
  auth_postgres_data: