services:
  auth-service:
    image: rahmanlibi47/auth-service:latest
    container_name: auth-service
    ports:
      - "8001:8001"
    env_file:
      - ./services/auth-service/.env.docker
    depends_on:
      postgres:
        condition: service_healthy

  job-tracker-redis:
    image: redis:7
    container_name: job-tracker-redis
    ports:
      - "6379:6379"

  client:
    image: rahmanlibi47/careerledger-client:latest
    container_name: careerledger-client
    ports:
      - "5173:80"

  application-service:
    image: rahmanlibi47/application-service:latest
    container_name: application-service
    ports:
      - "8002:8002"
    env_file:
      - ./services/application-service/.env.docker
    depends_on:
      postgres:
        condition: service_healthy
      job-tracker-redis:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3-management
    container_name: careerledger-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:17
    container_name: careerledger-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: careerledger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d careerledger"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: